babylonlabs-io/btc-staker

itest/e2e_test.go, staker/stakerapp.go, walletcontroller/client.go, walletcontroller/interface.go
Fixes: https://github.com/babylonlabs-io/btc-staker/issues/18
Fixes handling of the case in which program crashes in between sending of unbonding transactions and unbonding transaction confirmation.
Note: this is still not perfect, as it may happen that:
- user requests unbonding
- call is returned to the user about success
- program crashes before unbonding tx is sent to btc
- to handle this properly new state would need to be introduces `UNBONDING_REQUESTED` but this would be breaking change to existing db that we want to avoid rn.
Follow up task: https://github.com/babylonlabs-io/btc-staker/issues/19
=> Fix handling of the restart during unbonding

itest/bitcoind_node_setup.go, itest/containers/config.go, itest/e2e_test.go, staker/babylontypes.go, staker/stakerapp.go, walletcontroller/client.go, walletcontroller/interface.go
- Removes `DumpPrivateKey` from the staker codebase
- Uses `walletprocesspsbt` to sign taproot spends
- bump bitcoind to v26 in e2e test
=> Sign taproot thorugh psbt

cmd/stakercli/transaction/transactions.go, cmd/stakercli/transaction/transactions_test.go
Add command to build withdraw transactions and psbt packet
=> Add withdrawal command

babylonclient/babyloncontroller.go, babylonclient/interface.go, go.mod, go.sum, itest/babylon_node_handler.go, itest/e2e_test.go, staker/babylontypes.go, staker/stakerapp.go, staker/types.go, tools/go.mod, tools/go.sum
- bumps babylon version to the one with new params
Note: merge only after https://github.com/babylonlabs-io/babylon/pull/45 is merged
=> feat: parameters upgrade

cmd/stakerd/main.go, itest/e2e_test.go, stakerservice/service.go
Use ctx instead of signal.Interceptor (needed for parallel tests, and more idiomatic to pass ctx)
Parallel tests.
Speed up from `15m` without docker to `4m`
=> chore(e2e): parallel e2e

CHANGELOG.md, babylonclient/babyloncontroller.go, itest/e2e_test.go, staker/stakerapp.go, staker/types.go
Babylon introduced possiblity of receiving covenant signatures even after quorum is reached -  https://github.com/babylonlabs-io/babylon/pull/130
This pr fixes btc-staker to use only quorum of signatures when building unbonding tx witness.
=> Use only quorum number of covenant signature when building the witness

CHANGELOG.md, Dockerfile, babylonclient/babyloncontroller.go, babylonclient/msgsender.go, babylonclient/pop.go, cmd/stakercli/admin/admin.go, cmd/stakercli/daemon/daemoncommands.go, cmd/stakercli/transaction/parsers.go, cmd/stakercli/transaction/transactions.go, itest/e2e_test.go, staker/babylontypes.go, staker/stakerapp.go, stakercfg/config.go, stakerservice/client/rpcclient.go, stakerservice/service.go
The libraries that we depend to use int64 for satoshi amount denominations. To be fully compatible with them,
it is better if we use similar types instead of doing conversions.
Further, this PR fixes some other type conversions and minor errors found by gosec.
Edit: tried to bump babylon dependency as well, but needs a version to be released first.
=> chore: Use int64 for satoshi amount configs

CHANGELOG.md, staker/stakerapp.go
* run activation check in separate go routine after startup
=> backport: run activation check in separate go routine after startup (#57)

CHANGELOG.md, itest/e2e_test.go, staker/commands.go, staker/stakerapp.go, stakerdb/trackedtranactionstore.go, stakerdb/trackedtransactionstore_test.go, walletcontroller/client.go, walletcontroller/interface.go
- Do not use inputs which are already on babylon in new staking transactions when using pre-approval flow. This enables concurrent sending of pre-approvals
=> feature: do not use inputs already on babyon

CHANGELOG.md, itest/e2e_test.go, staker/babylontypes.go, staker/events.go, staker/stakerapp.go, staker/types.go, stakerdb/trackedtranactionstore.go
Fixes:
- https://github.com/babylonlabs-io/btc-staker/issues/63
- https://github.com/babylonlabs-io/btc-staker/issues/71
Bug introduced when adding pre-approval flow. Adding information about confirmin btc block was not properly handled.
=> Fix withdrawable transactions query

CHANGELOG.md, babylonclient/babyloncontroller.go, babylonclient/interface.go, staker/stakerapp.go
- adjust for allow list modification in babylon v0.16.0, new stake can't be created if allow list is enabled
=> Disallow creating new stake if allow list is enabled

CHANGELOG.md, babylonclient/babyloncontroller.go, babylonclient/interface.go, go.mod, go.sum, itest/containers/containers.go, staker/babylontypes.go, staker/stakerapp.go, staker/types.go
- bumps babylon to v18
- fixes incompatibilites
- used parameters based on inclusion block height to build delegations
=> bump babylon v18

CHANGELOG.md, babylonclient/keyringcontroller/codec.go, babylonclient/keyringcontroller/keyring.go, babylonclient/keyringcontroller/keyringcontroller.go, cmd/stakercli/main.go, cmd/stakercli/pop/pop.go, itest/e2e_test.go, staker/pop_creator.go
Inttroduces command to create PoP between phase-1 and phase-2
=> add command to generate pop

CHANGELOG.md, cmd/stakercli/pop/pop.go, cmd/stakercli/pop/pop_test.go, itest/testutil/appcli.go
This PR:
- let `generate-create-pop` output the result to a JSON file
- added `validate` pop cmd which takes the pop JSON file and verify pop
=> chore: Validate pop cmd

CHANGELOG.md, itest/containers/config.go
This PR fixes comments to https://github.com/babylonlabs-io/btc-staker/pull/114 and adds changelog for it
=> fix: fix comments to base branch

CHANGELOG.md, README.md, cmd/stakerd/main.go, metrics/prometheus.go, metrics/prometheus_test.go, stakercfg/metrics.go
https://github.com/babylonlabs-io/btc-staker/pull/138
=> chore: backport #138

CHANGELOG.md, itest/manager.go, stakercfg/babylon.go
- modified `stakercli admin dump-config` to generate the Babylon keyring backend as file
=> chore: set default keyring backend to file

CHANGELOG.md, staker/babylontypes.go, staker/types.go, utils/btc_utils.go, walletcontroller/client.go
- Add sanity checks for transactions standards to quickly catch up any non-compliant transactions
=> add sanity check for transactions standards

CHANGELOG.md, itest/e2e_restaking_test.go, itest/e2e_test.go, stakercfg/config.go
=> chore: change default max feerate

CHANGELOG.md, staker/stakerapp.go, walletcontroller/interface.go
Handles nil deref that happens if tx is in mempool, response and err returned are `nil` which we didn't handle
=> chore: spend stake check confirmation
